# Generated by Django 3.0.6 on 2020-09-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('tprojects', models.CharField(max_length=200)),
                ('tstart', models.DateTimeField()),
                ('tend', models.DateTimeField()),
                ('ttimer', models.DateTimeField()),
            ],
        ),
    ]
