# Generated by Django 3.0.6 on 2020-09-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tprojects',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('Android', 'Android')], max_length=200),
        ),
    ]
