# Generated by Django 3.0.6 on 2020-09-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeApp', '0002_auto_20200909_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ttimer',
        ),
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
