# Generated by Django 3.0.6 on 2020-09-09 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeApp', '0005_remove_task_ttimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
