# Generated by Django 3.0.6 on 2020-09-09 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeApp', '0006_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='tend',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tstart',
            field=models.TimeField(blank=True),
        ),
    ]
